/*
 * generated by Xtext 2.21.0
 */
package edu.uned.iss.tfm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AatDSLStandaloneSetup extends AatDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new AatDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
